/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    String testMe() {
        return "I need to be tested";
    }

    String anotherMethodToTest() {
        return "I also need to be tested";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
